"""
Django settings for promptRightProd project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
import dj_database_url  # Corrected import statement
from pathlib import Path
import urllib.parse
import os

import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APPS_DIR = BASE_DIR

# Load .env file from the project root (backend/grade_be directory)
env_path = BASE_DIR / '.env'

# Try loading .env file with explicit path and manual fallback
if env_path.exists():
    # Load with override=True to ensure variables are set
    result = dotenv.load_dotenv(dotenv_path=env_path, override=True)
    print(f"\n[DEBUG] .env file loading result: {result}")
    
    # Additional debug: Manually check if Azure vars are in the file
    # If dotenv didn't load them, try manual parsing
    if not os.environ.get('AZURE_ACCOUNT_NAME'):
        print(f"[DEBUG] dotenv didn't load AZURE_ACCOUNT_NAME, trying manual parse...")
        try:
            with open(env_path, 'r', encoding='utf-8') as f:
                content = f.read()
                print(f"[DEBUG] File size: {len(content)} characters")
                
                # Find all lines with AZURE
                azure_lines = [line for line in content.split('\n') if 'AZURE' in line.upper()]
                print(f"[DEBUG] Found {len(azure_lines)} lines with 'AZURE' in them")
                for i, line in enumerate(azure_lines[:5], 1):
                    print(f"[DEBUG]   Line {i}: {repr(line[:80])}")  # Show first 80 chars
                
                # Parse all lines
                parsed_count = 0
                for line in content.split('\n'):
                    original_line = line
                    line = line.strip()
                    # Skip comments and empty lines
                    if not line or line.startswith('#'):
                        continue
                    # Parse key=value pairs
                    if '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        value = value.strip().strip('"').strip("'")
                        # Set Azure variables manually
                        if key == 'AZURE_ACCOUNT_NAME':
                            os.environ['AZURE_ACCOUNT_NAME'] = value
                            print(f"[DEBUG] ✓ Manually set AZURE_ACCOUNT_NAME={value}")
                            parsed_count += 1
                        elif key == 'AZURE_ACCOUNT_KEY':
                            os.environ['AZURE_ACCOUNT_KEY'] = value
                            print(f"[DEBUG] ✓ Manually set AZURE_ACCOUNT_KEY (length={len(value)})")
                            parsed_count += 1
                        elif key == 'AZURE_CONTAINER':
                            os.environ['AZURE_CONTAINER'] = value
                            print(f"[DEBUG] ✓ Manually set AZURE_CONTAINER={value}")
                            parsed_count += 1
                
                print(f"[DEBUG] Total Azure variables parsed: {parsed_count}")
                if parsed_count == 0:
                    print(f"[DEBUG] WARNING: No Azure variables were found in .env file!")
                    print(f"[DEBUG] Searching for 'grademedia' in file: {'grademedia' in content}")
        except Exception as e:
            print(f"[DEBUG] Error manually parsing .env file: {e}")
            import traceback
            traceback.print_exc()
else:
    print(f"[DEBUG] .env file not found at: {env_path}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-temp-key-123')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# ALLOWED_HOSTS = ['promptrightprod.onrender.com' ,'http://localhost:5173','http://localhost:8000']

ALLOWED_HOSTS = ["*"]  # WARNING: Use this only for local testing!

CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://localhost:5173"]


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
OCR_OUTPUT_DIR = os.path.join(MEDIA_ROOT, "output")

# Azure Blob Storage Configuration (for production media files)
# Set these environment variables to enable Azure storage:
# - AZURE_ACCOUNT_NAME: Your storage account name
# - AZURE_ACCOUNT_KEY: Your storage account key (Key1)
# - AZURE_CONTAINER: Container name (default: 'media')
AZURE_ACCOUNT_NAME = os.environ.get("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.environ.get("AZURE_ACCOUNT_KEY")
AZURE_CONTAINER = os.environ.get("AZURE_CONTAINER", "media")

# Use Azure storage for media files if AZURE_ACCOUNT_NAME is configured
# Django 5.0+ uses STORAGES dict instead of DEFAULT_FILE_STORAGE

# Debug: Print environment variable values (without exposing the key)
print(f"\n{'='*60}")
print("AZURE STORAGE CONFIGURATION CHECK")
print(f"{'='*60}")
print(f"AZURE_ACCOUNT_NAME from env: {os.environ.get('AZURE_ACCOUNT_NAME', 'NOT SET')}")
print(f"AZURE_ACCOUNT_KEY from env: {'SET' if os.environ.get('AZURE_ACCOUNT_KEY') else 'NOT SET'}")
print(f"AZURE_CONTAINER from env: {os.environ.get('AZURE_CONTAINER', 'NOT SET')}")
print(f"AZURE_ACCOUNT_NAME variable: {AZURE_ACCOUNT_NAME}")
print(f".env file path: {env_path}")
print(f".env file exists: {env_path.exists()}")
print(f"{'='*60}\n")

# For local development, use local storage (even if Azure is configured)
# For production, Azure will be used via deployment_settings.py
# Only use Azure in settings.py if explicitly enabled via USE_AZURE_STORAGE env var
USE_AZURE_STORAGE = os.environ.get("USE_AZURE_STORAGE", "False").lower() == "true"

if AZURE_ACCOUNT_NAME and USE_AZURE_STORAGE:
    # Use Azure Blob Storage (for production or when explicitly enabled)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"
    print(f"[OK] Azure Blob Storage ENABLED (local development with Azure)")
    print(f"   Account: {AZURE_ACCOUNT_NAME}")
    print(f"   Container: {AZURE_CONTAINER}")
    print(f"   Media URL: {MEDIA_URL}")
else:
    # Default to local file storage for local development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    if AZURE_ACCOUNT_NAME:
        print(f"[INFO] Local file storage (Azure configured but USE_AZURE_STORAGE=False)")
        print(f"   Azure will be used in production via deployment_settings.py")
    else:
        print(f"[INFO] Local file storage (Azure not configured)")
    print(f"   Media Root: {MEDIA_ROOT}")


# Session and Cookie Settings
# SESSION_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SECURE = False
# Application definition
# If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-id',
]
# Increase session duration (example: 2 weeks)
# SESSION_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = True  # For HTTPS connections only
SESSION_COOKIE_SAMESITE = "Lax"  # Or 'Strict' for better security

SESSION_COOKIE_AGE = 1209600  # 2 weeks, in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

INSTALLED_APPS = [
    # 'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "corsheaders",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "authentication",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "storages",
    # 'collectfast',
    "prompts",
    "django_celery_beat",
    "django_celery_results",
    "celery",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "grade",
    "executor",
    "organization",
    "utils.apps.UtilsConfig",
]

# Admin emails - read from environment, with defaults for local dev
_admin_emails_env = os.environ.get("ADMIN_EMAILS", "rathika.selva@gmail.com,edricjsam@gmail.com,bharathiselvaraj23@outlook.com,suhita298@gmail.com")
ADMIN_EMAILS = [email.strip() for email in _admin_emails_env.split(",") if email.strip()]
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
    # Required for session-based authentication
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "authentication.middleware.TenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "utils.middleware.MyExceptionHandlerMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

ROOT_URLCONF = "promptRightProd.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "promptRightProd.wsgi.application"


# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ['DATABASE_URL'],
#         conn_max_age=600
#     )
# }
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "authentication.User"
# AUTH_USER_MODEL = "grade.User"

GOOGLE_CLIENT_ID = os.environ.get(
    "GOOGLE_CLIENT_ID",
    "987929579839-osrfs18jb5binb75mltbkttndm062e3u.apps.googleusercontent.com"  # Default for local dev
)

GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# Number of log backups to keep (default value, can be overridden by LogSetting)
LOG_BACKUP_COUNT = 10

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'rotating_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'grade_be.log'),
            'when': 'D',  # Rotate daily
            'interval': 1,
            'backupCount': LOG_BACKUP_COUNT,  # Use dynamic setting
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'delay': True,  # Delay file creation until the first log message
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'rotating_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['rotating_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'executor': {
            'handlers': ['console', 'rotating_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console', 'rotating_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'grade': {
            'handlers': ['console', 'rotating_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # Token/Cost logging from Gemini client
        'centralised_llm': {
            'handlers': ['console', 'rotating_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # HTTP request logging (optional - can be noisy)
        'httpx': {
            'handlers': ['rotating_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Google GenAI SDK logs
        'google_genai': {
            'handlers': ['rotating_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     # Other JWT settings...
# }

"""
API Credentials
"""


# OPENAI_API_KEY =
# os.getenv("MYDJANGOAPP_OPENAI_API_KEY")#settings.openai_api_key
# settings.organization_id  # Access the organization ID
ORGANIZATION_ID = os.getenv("MYDJANGOAPP_ORGANIZATION_ID")

API_VERSION= os.getenv("AZURE_OPENAI_API_VERSION") 
ENDPOINT= os.getenv("AZURE_OPENAI_ENDPOINT")
SUBSCRIPTION_KEY = os.getenv("AZURE_OPENAI_SUBSCRIPTION_KEY")
DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")  # Access the deployment name
OPENAI_API_KEY=os.getenv("MYDJANGOAPP_OPENAI_API_KEY")
TOGETHER_API_KEY=os.getenv("TOGETHER_API_KEY")
TOGETHER_API_BASE=os.getenv("TOGETHER_API_BASE")


# Sending Mail to App's Owner in case high level exception

# Gmail SMTP Configuration (for Production)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "solutionslysa@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")  # NEVER hardcode passwords!
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
SERVER_EMAIL = EMAIL_HOST_USER

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")

"""
# settings.py (for testing)
if 'test' in sys.argv:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
"""

# STORAGES
# ------------------------------------------------------------------------------
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
# AWS_ACCESS_KEY_ID = os.getenv("DJANGO_AWS_ACCESS_KEY_ID", default=None)
# # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
# AWS_SECRET_ACCESS_KEY = os.getenv("DJANGO_AWS_SECRET_ACCESS_KEY", default=None)
# # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
# AWS_STORAGE_BUCKET_NAME = os.getenv("DJANGO_AWS_STORAGE_BUCKET_NAME", default=None)
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
# AWS_QUERYSTRING_AUTH = False
# # DO NOT change these unless you know what you're doing.
# _AWS_EXPIRY = 60 * 60 * 24 * 7
# # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
# AWS_S3_OBJECT_PARAMETERS = {
#     "CacheControl": f"max-age={_AWS_EXPIRY}, s-maxage={_AWS_EXPIRY}, must-revalidate",
# }
# # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
# AWS_S3_MAX_MEMORY_SIZE = os.getenv(
#     "DJANGO_AWS_S3_MAX_MEMORY_SIZE",
#     default=100_000_000,  # 100MB
# )
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
# AWS_S3_REGION_NAME = os.getenv("DJANGO_AWS_S3_REGION_NAME", default=None)
# # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#cloudfront
# AWS_S3_CUSTOM_DOMAIN = os.getenv("DJANGO_AWS_S3_CUSTOM_DOMAIN", default=None)
# aws_s3_domain = AWS_S3_CUSTOM_DOMAIN or f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
# ------------------------
# COLLECTFAST_STRATEGY = "collectfast.strategies.boto3.Boto3Strategy"
# production = os.getenv("production")

# if production=="True":
#     print("on production")
#     STATIC_ROOT = str(BASE_DIR / "staticfiles")
#     STATIC_URL = f"https://{aws_s3_domain}/static/"
#     STATICFILES_STORAGE = "prompts.storages.StaticS3Storage"
#     # MEDIA
#     # ------------------------------------------------------------------
#     DEFAULT_FILE_STORAGE = "prompts.storages.MediaS3Storage"
#     MEDIA_URL = f"https://{aws_s3_domain}/media/"

# else:
#     STATIC_ROOT = str(BASE_DIR / "staticfiles")
#     STATIC_URL = "/static/"
# #CORS settings for REST APIs
# CORS_ALLOW_ALL_ORIGINS = True # If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
# CORS_ALLOW_CREDENTIALS = True
# # CORS_ALLOWED_ORIGINS = [
# #     'http://3.110.10.173:3000','http://localhost:3000',
# # ] # If this is used, then not need to use `CORS_ALLOW_ALL_ORIGINS = True`

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Remove the following line
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CORS_ALLOWED_ORIGIN_REGEXES = [
    "http://3.110.10.173:3000",
    "http://localhost:3000",
    "http://localhost:5173",
]

RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")
RAZORPAY_KEY = os.getenv("RAZORPAY_KEY")
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY")


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}


CORS_ORIGIN_WHITELIST = [
    "http://localhost:8080",
    "http://localhost:3000",
    "http://localhost:5173",
    # Add other frontend URLs as needed
]

# Session settings
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Session and CSRF settings
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}
CORS_ALLOW_ALL_ORIGINS = True  # For development only, restrict in production
CORS_ALLOW_CREDENTIALS = True

# Celery Configuration with Redis
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")

CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"