# Generated by Django 5.1.9 on 2026-01-28 09:31

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('OCR', 'OCR'), ('GRADING', 'Grading')], max_length=20)),
                ('identifier', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answer_uploads/')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('question_paper_type', models.CharField(max_length=20)),
                ('question_paper_id', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ocr_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_json_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ocr_images_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ocr_error', models.TextField(blank=True, null=True)),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Attempt number for this test submission (1 = first attempt)')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_text', models.TextField()),
                ('allocated_marks', models.FloatField()),
                ('obtained_marks', models.FloatField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('mistakes_found', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Criteria Grades',
            },
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField()),
                ('marks_out_of', models.FloatField()),
                ('complexity', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('test_title', models.CharField(blank=True, max_length=255, null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('questions', models.JSONField(blank=True, default=list, null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('max_retakes', models.PositiveIntegerField(default=5, help_text='Maximum number of retakes allowed for this question paper (1-10)')),
                ('file', models.FileField(upload_to='question_papers/generated/')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name=authentication.models.User)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('total_score', models.FloatField(default=0)),
                ('max_possible_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('result_json_path', models.CharField(blank=True, max_length=500, null=True)),
                ('grading_processed', models.BooleanField(default=False)),
                ('grading_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('questions_count', models.IntegerField(default=0)),
                ('diagrams_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'grading_results',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('board', models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('TNboard', 'TNboard'), ('Neet', 'NEET'), ('Jee', 'JEE')], max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('evaluator', 'Evaluator'), ('mentor', 'Mentor')], default='mentor', max_length=20)),
                ('recipient_role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('evaluator', 'Evaluator'), ('mentor', 'Mentor')], default='student', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('mentor_request', models.BooleanField(default=False)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('on_click_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousYearQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('test_title', models.CharField(blank=True, max_length=255, null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('questions', models.JSONField(blank=True, default=list, null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('max_retakes', models.PositiveIntegerField(default=5, help_text='Maximum number of retakes allowed for this question paper (1-10)')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('set_number', models.CharField(blank=True, help_text='Official set number for this previous year question paper (auto-extracted from filename).', max_length=50, null=True)),
                ('qp_code', models.CharField(blank=True, help_text='Official question paper code (QP code) for this paper (auto-extracted from filename).', max_length=50, null=True)),
                ('answer_key', models.FileField(blank=True, help_text='Upload the answer key (PDF or JSON). JSON is recommended for higher accuracy.', null=True, upload_to='answer_keys/previous_year/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'json'])])),
                ('answer_key_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('assets', models.JSONField(blank=True, default=dict)),
                ('new_asset_file', models.FileField(blank=True, help_text='Upload a single asset here to add it to the Assets list.', null=True, upload_to='question_papers/previous_year/assets/')),
                ('new_asset_label', models.CharField(blank=True, help_text="Question Number (e.g. 'Q4'). LEAVE BLANK to auto-extract from filename (e.g. '..._Q4.png')", max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State Board', 'State Board'), ('JEE', 'JEE'), ('NEET', 'NEET')], max_length=50)),
                ('complexity', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('question_type', models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('short-answer', 'Short Answer'), ('long-answer', 'Long Answer')], max_length=50)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('explanation_image', models.ImageField(blank=True, null=True, upload_to='explanation_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=50)),
                ('question_type', models.CharField(blank=True, max_length=50, null=True)),
                ('allocated_marks', models.FloatField()),
                ('obtained_marks', models.FloatField()),
                ('student_answer', models.JSONField(blank=True, null=True)),
                ('expected_answer', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('mistakes_identified', models.JSONField(default=list)),
                ('final_feedback', models.TextField(blank=True, null=True)),
                ('general_feedback', models.TextField(blank=True, null=True)),
                ('diagram_comparison', models.TextField(blank=True, null=True)),
                ('concept_analysis', models.JSONField(blank=True, null=True)),
                ('confidence_percentage', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('test_title', models.CharField(blank=True, max_length=255, null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('questions', models.JSONField(blank=True, default=list, null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('max_retakes', models.PositiveIntegerField(default=5, help_text='Maximum number of retakes allowed for this question paper (1-10)')),
                ('file', models.FileField(upload_to='question_papers/qp_uploader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('test_title', models.CharField(blank=True, max_length=255, null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('questions', models.JSONField(blank=True, default=list, null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('max_retakes', models.PositiveIntegerField(default=5, help_text='Maximum number of retakes allowed for this question paper (1-10)')),
                ('file', models.FileField(upload_to='question_papers/sample/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
