# Generated by Django 5.1.9 on 2026-01-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0039_permission_product_tenant_userpii_and_more'),
        ('grade', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimetrics',
            name='student_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_metrics', to='organization.studentanswer'),
        ),
        migrations.AddField(
            model_name='answerassignment',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerupload',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_uploads', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='answerupload',
            name='organization_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.test'),
        ),
        migrations.AddField(
            model_name='answerassignment',
            name='answer_upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grade.answerupload'),
        ),
        migrations.AddField(
            model_name='aimetrics',
            name='answer_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_metrics', to='grade.answerupload'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='boards',
            field=models.ManyToManyField(related_name='evaluators', to='grade.board'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='answer_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='grade.answerupload'),
        ),
        migrations.AddField(
            model_name='generatedquestionpaper',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_papers', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='answerupload',
            name='generated_question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.generatedquestionpaper'),
        ),
        migrations.AddField(
            model_name='gradingresult',
            name='answer_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_results', to='grade.answerupload'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='languages',
            field=models.ManyToManyField(related_name='evaluators', to='grade.language'),
        ),
        migrations.AddField(
            model_name='mainrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorstudent',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_by_mentors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previousyearquestionpaper',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_papers', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='answerupload',
            name='previous_year_question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.previousyearquestionpaper'),
        ),
        migrations.AddField(
            model_name='questionfeedback',
            name='answer_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='grade.answerupload'),
        ),
        migrations.AddField(
            model_name='questiongrade',
            name='grading_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_grades', to='grade.gradingresult'),
        ),
        migrations.AddField(
            model_name='criteriagrade',
            name='question_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_grades', to='grade.questiongrade'),
        ),
        migrations.AddField(
            model_name='questions',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_papers', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='answerupload',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.questions'),
        ),
        migrations.AddField(
            model_name='samplequestionpaper',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_papers', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='answerupload',
            name='sample_question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.samplequestionpaper'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='subjects',
            field=models.ManyToManyField(related_name='evaluators', to='grade.subject'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['user_id'], name='grading_res_user_id_d0d380_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['answer_upload'], name='grading_res_answer__5dff05_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingresult',
            index=models.Index(fields=['created_at'], name='grading_res_created_f30862_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorstudent',
            unique_together={('mentor', 'student')},
        ),
        migrations.AddIndex(
            model_name='previousyearquestionpaper',
            index=models.Index(fields=['qp_code', 'set_number'], name='grade_previ_qp_code_7b7de2_idx'),
        ),
        migrations.AddIndex(
            model_name='previousyearquestionpaper',
            index=models.Index(fields=['board', 'subject', 'year'], name='grade_previ_board_56f037_idx'),
        ),
        migrations.AddIndex(
            model_name='answerupload',
            index=models.Index(fields=['user_id', 'question_paper_type', 'question_paper_id'], name='grade_answe_user_id_8a628d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerupload',
            unique_together={('user_id', 'question_paper_type', 'question_paper_id', 'attempt_number')},
        ),
    ]
