# Generated by Django 5.0.1 on 2024-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_alter_user_groups_alter_user_user_permissions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="free_trial_hits",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
