# Generated by Django 5.0.1 on 2024-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_free_trial_hits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="free_trial_hits",
            field=models.IntegerField(default=0),
        ),
    ]
