# Generated by Django 5.0.6 on 2024-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_free_trial_hits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("mentor", "Mentor"),
                    ("admin", "Admin"),
                    ("evaluator", "Evaluator"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
