# Generated by Django 5.0.6 on 2025-02-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_user_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("mentor", "Mentor"),
                    ("admin", "Qp Uploader"),
                    ("evaluator", "Evaluator"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
