# Generated by Django 5.0.6 on 2025-02-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_role_name_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subjects",
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("mentor", "Mentor"),
                    ("admin", "Admin"),
                    ("evaluator", "Evaluator"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
