# Generated by Django 5.0.6 on 2025-02-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0014_user_address_line1_user_address_line2_user_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
