# Generated by Django 5.0.6 on 2025-04-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0022_alter_paymenttransaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("evaluator", "Evaluator"),
                    ("qp_uploader", "QP Uploader"),
                    ("mentor", "Mentor"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.JSONField(default=list),
        ),
    ]
