# Generated by Django 5.1.9 on 2025-05-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_invoice_invoiceitem_usagehistory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="usagehistory",
            name="user",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
        migrations.DeleteModel(
            name="UsageHistory",
        ),
    ]
