# Generated by Django 5.1.9 on 2025-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0027_remove_invoiceitem_invoice_remove_usagehistory_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="razorpay_invoice_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
