# Generated by Django 5.1.9 on 2025-06-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0031_user_is_admin_alter_user_google_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
