# Generated by Django 5.1.9 on 2026-01-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_profile_picture'),
        ('authentication', '0037_remove_user_is_evaluator_remove_user_is_mentor_and_more'),
    ]

    operations = [
    ]
