# Generated by Django 5.0.1 on 2024-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="cost",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
