# Generated by Django 5.0.6 on 2024-08-04 12:44

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0008_emailwriter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "num_questions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bloom",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "num_options",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "option_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "num_missing_words",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representing_words",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "num_items",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "learning_obj",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provide_answer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "explanation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "format_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GeneratedQuestion",
                "verbose_name_plural": "GeneratedQuestions",
            },
        ),
    ]
