# Generated by Django 5.0.6 on 2025-04-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0009_generatedquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("hits_remaining", models.PositiveIntegerField(default=3)),
                ("first_hit_time", models.DateTimeField(auto_now_add=True)),
                ("last_hit_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anonymous Usage",
                "verbose_name_plural": "Anonymous Usages",
                "unique_together": {("ip_address",)},
            },
        ),
    ]
