# Generated by Django 5.1.9 on 2025-06-21 04:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0011_alter_anonymoususage_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "emoji_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("neutral", "Neutral"),
                            ("bad", "Bad"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feedback",
                "verbose_name_plural": "User Feedbacks",
                "indexes": [
                    models.Index(
                        fields=["user"], name="prompts_use_user_id_da2d0f_idx"
                    ),
                    models.Index(
                        fields=["emoji_rating"],
                        name="prompts_use_emoji_r_f9d9b3_idx",
                    ),
                    models.Index(
                        fields=["created"],
                        name="prompts_use_created_6e3153_idx",
                    ),
                ],
            },
        ),
    ]
