# Generated by Django 5.0.6 on 2025-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_role_remove_user_role_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
