# Generated by Django 5.0.6 on 2025-05-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_user_active_role_user_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active_role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
    ]
