# Generated by Django 5.1.9 on 2025-06-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_usagehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagehistory",
            name="reference_id",
        ),
    ]
