# Generated by Django 5.0.1 on 2024-03-10 16:59

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0002_translation_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPhits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hits", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
