# Generated by Django 5.0.1 on 2024-04-02 10:33

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0003_iphits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "orderID",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Order AMount",
                    ),
                ),
                (
                    "paymentStatus",
                    models.CharField(
                        blank=True,
                        choices=[("success", "success"), ("failed", "failed")],
                        max_length=250,
                        null=True,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
