# Generated by Django 5.0.1 on 2024-04-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0004_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paymentStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "success"),
                    ("failed", "failed"),
                    ("in-progress", "in-progress"),
                ],
                default="in-progress",
                max_length=250,
                null=True,
                verbose_name="Payment Status",
            ),
        ),
    ]
