# Generated by Django 5.0.6 on 2024-06-19 05:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0005_alter_subscription_paymentstatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transliteration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "input_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "input_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "input_destination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "output_response",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "cost",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transliterations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transliteration",
                "verbose_name_plural": "Transliterations",
            },
        ),
    ]
