# Generated by Django 5.0.6 on 2024-06-23 16:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0007_alter_subscription_amount_entity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailWriter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "selectedType",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "purpose",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("personalized", models.TextField(blank=True, null=True)),
                ("generated_email", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EmailWriter",
                "verbose_name_plural": "EmailWriters",
            },
        ),
    ]
