# Generated by Django 5.0.6 on 2025-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0010_anonymoususage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="anonymoususage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="anonymoususage",
            name="ip_address",
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AddIndex(
            model_name="anonymoususage",
            index=models.Index(
                fields=["ip_address"], name="prompts_ano_ip_addr_df2f21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymoususage",
            index=models.Index(
                fields=["first_hit_time"],
                name="prompts_ano_first_h_528066_idx",
            ),
        ),
    ]
