# Generated by Django 5.1.9 on 2025-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backup_count", models.PositiveIntegerField(default=10)),
            ],
            options={
                "verbose_name_plural": "Log Settings",
            },
        ),
    ]
